(()=>{
'use strict';
const $=id=>document.getElementById(id);
const words={en:{title:"Gabby's Little World",hi:"Hi, Gabby!",choose:"What shall we play?",trace:"Finger Tracing",color:"Color & Draw",match:"Match the Friends",count:"Count With Me",shapes:"Shape Garden",sounds:"Animal Sounds",home:"Home",again:"Again!",next:"Next",yay:"You did it!",touch:"Use your finger to follow the sparkly path!",tap:"Tap the picture!",clear:"Clear",parent:"Grown-ups",voice:"Voice",soundOn:"Sound on",soundOff:"Sound off",try:"Let's try together!",find:"Find the",done:"Wonderful!",settings:"Settings",voices:"Choose voice",speed:"Voice speed",good:"Great job!",slow:"Follow the dots with your finger.",star:"A star!",circle:"A circle!",heart:"A heart!"},es:{title:"El Mundito de Gabby",hi:"¡Hola, Gabby!",choose:"¿A qué jugamos?",trace:"Trazar",color:"Pintar",match:"Parejas",count:"Contemos",shapes:"Jardín de Formas",sounds:"Sonidos de Animales",home:"Inicio",again:"¡Otra vez!",next:"Siguiente",yay:"¡Lo lograste!",touch:"¡Sigue el caminito brillante con tu dedo!",tap:"¡Toca la imagen!",clear:"Borrar",parent:"Adultos",voice:"Voz",soundOn:"Con sonido",soundOff:"Sin sonido",try:"¡Vamos juntas!",find:"Busca",done:"¡Maravilloso!",settings:"Opciones",voices:"Elegir voz",speed:"Velocidad",good:"¡Muy bien!",slow:"Sigue los puntos con tu dedo.",star:"¡Una estrella!",circle:"¡Un círculo!",heart:"¡Un corazón!"}};
let lang=localStorage.getItem('gabby-language')||'en',muted=localStorage.getItem('gabby-muted')==='1',speed=Number(localStorage.getItem('gabby-speed')||'.85'),chosen=localStorage.getItem('gabby-voice')||'',voices=[],current='home',round=0,strokes=[],progress=JSON.parse(localStorage.getItem('gabby-v3-progress')||'{"plays":0,"stars":0}'),cleanup=()=>{};
const tr=k=>words[lang][k],q=s=>JSON.stringify(s),random=a=>a[Math.floor(Math.random()*a.length)];
function getVoices(){if(!('speechSynthesis'in window))return [];voices=speechSynthesis.getVoices().filter(v=>v.lang.toLowerCase().startsWith(lang));return voices}
function talk(message){if(muted||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(message);utterance.lang=lang==='es'?'es-ES':'en-US';utterance.rate=speed;utterance.pitch=1.1;const pool=getVoices();utterance.voice=pool.find(v=>v.voiceURI===chosen)||pool.find(v=>/premium|enhanced|samantha|ava|sofia|monica/i.test(v.name))||pool.find(v=>v.localService)||pool[0]||null;speechSynthesis.speak(utterance)}catch(e){}}
if('speechSynthesis'in window){speechSynthesis.onvoiceschanged=getVoices;getVoices()}
function show(html){cleanup();cleanup=()=>{};$('screen').innerHTML=html;$('brand').textContent=tr('title');$('language').textContent=lang==='en'?'ES':'EN';document.documentElement.lang=lang}
function b(label,fn,cls='pill'){const el=document.createElement('button');el.className=cls;el.textContent=label;el.onclick=fn;return el}
function say(msg){talk(msg)}
function stars(){progress.stars++;progress.plays++;localStorage.setItem('gabby-v3-progress',JSON.stringify(progress));}
function nav(){return '<button class="go-home" id="back" aria-label="Home">🏡</button>'}
function bindHome(){$('back').onclick=home}
function home(){current='home';show('<div class="hero"><div class="hero-art">🌈 🦋 🌼</div><h1>'+tr('hi')+'</h1><p>'+tr('choose')+'</p></div><div class="play-grid">'+[['trace','✏️','peach'],['color','🎨','lavender'],['match','🧸','yellow'],['count','🍓','mint'],['shapes','🔵','blue'],['sounds','🐶','pink']].map(([k,e,c])=>'<button class="big-tile '+c+'" data-play="'+k+'"><span class="tile-emoji">'+e+'</span><span>'+tr(k)+'</span></button>').join('')+'</div>');document.querySelectorAll('[data-play]').forEach(x=>x.onclick=()=>start(x.dataset.play));}
function start(m){current=m;round=0;if(m==='trace')return trace();if(m==='color')return draw();if(m==='match')return match();if(m==='count')return count();if(m==='shapes')return shape();if(m==='sounds')return animal();}
function lesson(title,emoji,instruction){show(nav()+'<section class="play-panel"><h2>'+emoji+' '+title+'</h2><button class="speak" id="say" aria-label="Hear instructions">🔊</button><p class="instruction">'+instruction+'</p><div id="game"></div><div id="game-footer"></div></section>');bindHome();$('say').onclick=()=>say(instruction);}
function celebrate(next){stars();const c=$('game-footer');c.innerHTML='<div class="celebration" role="status">⭐ 🎉 ⭐<p>'+tr('yay')+'</p></div>';say(tr('good'));c.appendChild(b('🌈 '+tr('next'),next,'pill primary'));}
const shapes=[{name:'circle',en:'Circle',es:'Círculo',points:Array.from({length:101},(_,i)=>{let a=-Math.PI/2+i*Math.PI*2/100;return [.5+.35*Math.cos(a),.51+.35*Math.sin(a)]})},{name:'line',en:'Line',es:'Línea',points:Array.from({length:81},(_,i)=>[.15+.7*i/80,.52])},{name:'wave',en:'Wave',es:'Ola',points:Array.from({length:101},(_,i)=>[.12+.76*i/100,.5+.21*Math.sin(i/100*Math.PI*4)])},{name:'triangle',en:'Triangle',es:'Triángulo',points:poly([[.5,.14],[.86,.82],[.14,.82],[.5,.14]])},{name:'square',en:'Square',es:'Cuadrado',points:poly([[.19,.18],[.81,.18],[.81,.82],[.19,.82],[.19,.18]])},{name:'heart',en:'Heart',es:'Corazón',points:Array.from({length:121},(_,i)=>{const t=i/120*Math.PI*2;return [.5+(16*Math.sin(t)**3)/44,.48-(13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t))/48]})}];
function poly(vertices){let arr=[];for(let i=1;i<vertices.length;i++)for(let k=0;k<=25;k++)arr.push([vertices[i-1][0]+(vertices[i][0]-vertices[i-1][0])*k/25,vertices[i-1][1]+(vertices[i][1]-vertices[i-1][1])*k/25]);return arr}
function tracingShape(){return shapes[round%shapes.length]}
function trace(){let model=tracingShape();lesson(tr('trace'),'✏️',tr('touch'));const game=$('game');game.innerHTML='<div class="trace-name">'+(lang==='en'?model.en:model.es)+'</div><canvas id="trace-board" class="trace-board" aria-label="Trace the shape"></canvas><div class="trace-help">☝️ ✨</div>';const canvas=$('trace-board'),ctx=canvas.getContext('2d');let width=0,height=0,active=false,visited=new Set(),last=-1;const points=model.points;function resize(){const box=canvas.getBoundingClientRect();width=box.width;height=box.height;const dpi=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(width*dpi);canvas.height=Math.round(height*dpi);ctx.setTransform(dpi,0,0,dpi,0,0);paint()}function point(i){return [points[i][0]*width,points[i][1]*height]}function paint(){ctx.clearRect(0,0,width,height);ctx.fillStyle='#fffaf5';ctx.fillRect(0,0,width,height);ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();points.forEach((v,i)=>{const [x,y]=point(i);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.lineWidth=31;ctx.strokeStyle='#f4e2cc';ctx.stroke();ctx.setLineDash([1,19]);ctx.lineWidth=7;ctx.strokeStyle='#e3a26e';ctx.stroke();ctx.setLineDash([]);if(visited.size){ctx.strokeStyle='#7ebfa6';ctx.lineWidth=22;ctx.beginPath();let prev=-10;[...visited].sort((a,b)=>a-b).forEach(i=>{let [x,y]=point(i);if(i-prev>3)ctx.moveTo(x,y);else ctx.lineTo(x,y);prev=i});ctx.stroke()}let idx=0;while(idx<points.length&&visited.has(idx))idx++;const [sx,sy]=point(Math.min(idx,points.length-1));ctx.fillStyle='#f6ba45';ctx.beginPath();ctx.arc(sx,sy,16,0,2*Math.PI);ctx.fill();ctx.font='27px sans-serif';ctx.fillText('✨',sx-13,sy-25)}
function stroke(e){const bounds=canvas.getBoundingClientRect(),x=e.clientX-bounds.left,y=e.clientY-bounds.top;let best=Infinity,index=-1;for(let i=0;i<points.length;i++){let [px,py]=point(i),distance=Math.hypot(px-x,py-y);if(distance<best){best=distance;index=i}}if(best>Math.max(36,width*.095))return;const start=last<0?0:last;if(last<0&&index>15)return;if(last>=0&&index>last+22)return;const from=Math.max(0,last<0?0:Math.min(last,index)),to=Math.max(index,last);for(let j=from;j<=to;j++)visited.add(j);last=Math.max(last,index);paint();if(visited.size/points.length>.80){canvas.style.pointerEvents='none';celebrate(()=>{round++;trace()})}}
const down=e=>{active=true;canvas.setPointerCapture(e.pointerId);stroke(e)},move=e=>{if(active)stroke(e)},up=()=>active=false;canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);window.addEventListener('resize',resize);cleanup=()=>window.removeEventListener('resize',resize);resize();setTimeout(()=>{if(current==='trace')say(tr('slow'))},300)}
function draw(){lesson(tr('color'),'🎨',lang==='en'?'Paint with your finger!':'¡Pinta con tu dedito!');$('game').innerHTML='<div class="palette">'+['#ed7b86','#f8b754','#f4d86f','#6fc9a5','#67b4e5','#aa94dc','#574b66'].map(c=>'<button class="swatch" data-color="'+c+'" style="background:'+c+'"></button>').join('')+'</div><canvas id="drawing" class="drawing"></canvas>';$('game-footer').appendChild(b('🧽 '+tr('clear'),()=>{ctx.clearRect(0,0,canvas.width,canvas.height)},'pill'));const canvas=$('drawing'),ctx=canvas.getContext('2d'),rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.lineWidth=16;ctx.lineCap='round';ctx.lineJoin='round';let ink='#ed7b86',pressed=false;document.querySelectorAll('[data-color]').forEach(el=>el.onclick=()=>ink=el.dataset.color);const pos=e=>[e.clientX-canvas.getBoundingClientRect().left,e.clientY-canvas.getBoundingClientRect().top];canvas.onpointerdown=e=>{pressed=true;canvas.setPointerCapture(e.pointerId);ctx.beginPath();ctx.strokeStyle=ink;ctx.moveTo(...pos(e));ctx.lineTo(...pos(e));ctx.stroke()};canvas.onpointermove=e=>{if(pressed){ctx.lineTo(...pos(e));ctx.stroke()}};canvas.onpointerup=canvas.onpointercancel=()=>pressed=false;say(lang==='en'?'Paint with your finger!':'¡Pinta con tu dedito!')}
function choices(items,correct,instruction,next){lesson(tr(current),current==='count'?'🍓':current==='sounds'?'🐶':'🌼',instruction);$('game').innerHTML='<div class="picture-choices">'+items.map((it,i)=>'<button class="picture-option" data-index="'+i+'">'+it+'</button>').join('')+'</div>';document.querySelectorAll('[data-index]').forEach((el,i)=>el.onclick=()=>{if(items[i]!==correct){el.classList.add('nudge');setTimeout(()=>el.classList.remove('nudge'),430);say(tr('try'));return}document.querySelectorAll('[data-index]').forEach(x=>x.disabled=true);el.classList.add('win');celebrate(next)});setTimeout(()=>say(instruction),100)}
function count(){const n=1+round%3,fruit=['🍓','🍎','🍌'][round%3];const answer=String(n),opts=[1,2,3].map(String);choices(opts,answer,(lang==='en'?'How many '+fruit+'?':'¿Cuántas '+fruit+'?')+' '+fruit.repeat(n),()=>{round++;count()});$('game').insertAdjacentHTML('afterbegin','<div class="count-fruit">'+fruit.repeat(n)+'</div>')}
function shape(){const all=['🔴','🟦','🔺'];const i=round%3;choices(all,all[i],(lang==='en'?['Find the circle','Find the square','Find the triangle']:['Busca el círculo','Busca el cuadrado','Busca el triángulo'])[i],()=>{round++;shape()})}
function animal(){const all=['🐱','🐶','🐮'];const i=round%3;const noises=lang==='en'?['Meow! Find the cat.','Woof woof! Find the dog.','Moo! Find the cow.']:['¡Miau! Busca el gato.','¡Guau guau! Busca el perro.','¡Muuu! Busca la vaca.'];choices(all,all[i],noises[i],()=>{round++;animal()})}
function match(){const pairs=[['🐻','🐻','🐰'],['🍎','🍎','🍌'],['🐶','🐶','🐱'],['🚗','🚗','🚌']];const p=pairs[round%pairs.length],answer=p[0];choices([p[1],p[2]],answer,lang==='en'?'Find my friend! '+p[0]:'¡Encuentra mi pareja! '+p[0],()=>{round++;match()});$('game').insertAdjacentHTML('afterbegin','<div class="match-target">'+p[0]+'</div>')}
function settings(){current='settings';show(nav()+'<section class="play-panel"><h2>⚙️ '+tr('settings')+'</h2><button id="toggle" class="pill">'+(muted?tr('soundOff'):tr('soundOn'))+'</button><p>'+tr('voices')+'</p><select id="voices" class="voice-select"></select><p>'+tr('speed')+'</p><input id="rate" type="range" min=".7" max="1.1" step=".05" value="'+speed+'"><button id="sample" class="pill primary">🔊 '+tr('voice')+'</button><p class="fineprint">'+(lang==='en'?'Voice options depend on the voices installed on this device.':'Las voces dependen de las opciones instaladas en este dispositivo.')+'</p><p>⭐ '+progress.stars+' · 🎨 '+progress.plays+'</p></section>');bindHome();const v=$('voices');let pool=getVoices();v.innerHTML='<option value="">'+(lang==='en'?'Automatic voice':'Voz automática')+'</option>'+pool.map(x=>'<option value="'+x.voiceURI.replaceAll('"','&quot;')+'">'+x.name+'</option>').join('');v.value=chosen;v.onchange=()=>{chosen=v.value;localStorage.setItem('gabby-voice',chosen)};$('rate').oninput=e=>{speed=+e.target.value;localStorage.setItem('gabby-speed',speed)};$('toggle').onclick=()=>{muted=!muted;localStorage.setItem('gabby-muted',muted?'1':'0');$('toggle').textContent=muted?tr('soundOff'):tr('soundOn')};$('sample').onclick=()=>say(tr('hi')+' '+tr('choose'))}
$('home').onclick=home;$('parent').onclick=settings;$('language').onclick=()=>{lang=lang==='en'?'es':'en';chosen='';localStorage.setItem('gabby-language',lang);home()};home();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();